services:
  - type: web
    name: bsky-first-timers
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /
    autoDeploy: true
